CREATE USER 'app_user'@'%' IDENTIFIED BY 'password';

CREATE SCHEMA `csye6225` DEFAULT CHARACTER SET utf8;

GRANT INSERT, CREATE, ALTER, UPDATE, SELECT, REFERENCES on myapp.*
TO 'app_user'@'%' IDENTIFIED BY 'password'
WITH GRANT OPTION;